import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "A photo gallery app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div>{children}</div>
        <div id="modal-root-content" />
      </body>
    </html>
  );
}
